#image: ubuntu:latest
#
#before_script:
#  - 'apt-get update -y && apt-get install openssh-client -y'
#  - mkdir -p ~/.ssh
#  - eval $(ssh-agent -s)
#  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#  - ssh-add <(echo "$SSH_PRIVATE_KEY")
#  - ssh-keyscan -H '91.206.200.121' >> ~/.ssh/known_hosts

deploy_prod:
  stage: deploy
  environment:
    name: Production
  script:
    - echo "start!"
    - ssh freemark@91.206.200.121 "cd /home/freemark/sdelivery.dn.ua && chmod 766 deploy.sh && ./deploy.sh"
  only:
    - master