<?php

namespace console\controllers;



use common\models\Log;
use console\controllers\Parser\metro\CategoryParser;
use console\controllers\Parser\metro\ItemParse;
use yii\console\Controller;

class MetroParserController extends Controller
{
    const TIMEOUT = 60;

    private $afishaTypes = [
        'newyear',
        'concerts',
        'theatres',
        'circus',
        'clubs',
        'excursions',
        'festivals',
        'child',
        'sport',
        'exhibitions',
        'poetry',
        'seminars',
        'quest',
    ];
    private $response;
    public $active_cities;

    public function init()
    {
        $this->response = [
            'success' => [
                'HTTP/1.1 200 OK',
                'HTTP/1.0 200 OK',
                'HTTP/1.1 301 Moved Permanently',
            ],
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Парсит список городов и добавляет в кеш
     */
    public function actionParseCategory(){//парс всех категорий из сайта метро(осторожно на сайте метро около 1000 категорий)
        $link = new CategoryParser('https://metro.zakaz.ua/ru/', self::TIMEOUT);
        $link->downloadContent()->parseData();
    }
    public function actionParseItem(){//парс всех айтемов по категориям которые находяться в базе
        $link = new ItemParse();
        if($link->parseData()){
            $log = new Log();
            $log->message='Parse success';
            echo "\n".$log->message;
            $log->save();
        }
    }
}