<?php

namespace console\controllers;

use common\models\Log;
use console\controllers\Parser\metro\ItemParse;
use console\controllers\Parser\metro\PhotoParse;
use yii\console\Controller;

class MetroParserController extends Controller
{
    const TIMEOUT = 60;

    private $response;
    public $active_cities;

    public function init()
    {
        $this->response = [
            'success' => [
                'HTTP/1.1 200 OK',
                'HTTP/1.0 200 OK',
                'HTTP/1.1 301 Moved Permanently',
            ],
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        //парс всех айтемов по категориям которые находяться в базе
        $link = new ItemParse();
        if($link->parseData()){
            $message = 'Parse success';
            echo "\n" . $message;
            Log::write($message);
        }
    }

    public function actionPhoto()
    {
        //парс всех айтемов по категориям которые находяться в базе
        $link = new PhotoParse();
        if($link->parseData()){
            $message = 'Parse image success';
            echo "\n" . $message;
            Log::write($message);
        }
    }
}